config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  root 'pages#home'

  get 'recruiters/sign_up' => 'recruiters#sign_up'
  get 'employers/sign_up' => 'employers#sign_up'

  get 'recruiter_dash' => 'recruiter_dashboard#index'
  get 'employer_dash' => 'employer_dashboard#index'

  get "recruiter" => "pages#recruiter" #creates recruiter path
  get "employer" => "pages#employer" #creates employer  path
  get "postings" => "pages#postings" #creates postings path
  get "testing" => "pages#testing" #creates test path
  get "learn" => "pages#learn" #creates learn path
  get "how_to_recruiter" => "pages#how_to_recruiter" #creates how_to_recruiter path
  get "how_to_employer" => "pages#how_to_employer" #creates how_to_employer path
  get "payments" => "pages#payments" #creates payments path

 

end

app/models/users/admin.rb
class Admin < User

end

app/models/users/employer.rb
class Employer < User

end

app/models/users/recruiter.rb
class Recruiter < User

end

app/models/users/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
         :omniauth_providers => [:google_oauth2, :facebook, :linkedin]

  def full_name
    first_name + ' ' + last_name
  end

  #def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
  #  data = access_token.info
  #  user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
  #  if user
  #    return user
  #  else
  #    registered_user = User.where(:email => access_token.info.email).first
  #     if registered_user
  #      return registered_user
  #     else
  #      user = User.create(name: data["name"],
  #                        provider:access_token.provider,
  #                        email: data["email"],
  #                        uid: access_token.uid ,
  #                        password: Devise.friendly_token[0,20],
  #      )
  #     end
  #  end
  #
  #end
  #
  #def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  # user = User.where(:provider => auth.provider, :uid => auth.uid).first
  # if user
  #   return user
  #  else
  #    registered_user = User.where(:email => auth.info.email).first
  #    if registered_user
  #      return registered_user
  #    else
  #      user = User.create(name:auth.extra.raw_info.name,
  #                         provider:auth.provider,
  #                         uid:auth.uid,
  #                         email:auth.info.email,
  #                         password:Devise.friendly_token[0,20]
  #                        )
  #    end
  #  end
  #end
  #
  #
  #def self.connect_to_linkedin(auth, signed_in_resource=nil)
  #  user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #  if user
  #    return user
  #  else
  #    registered_user = User.where(:email => auth.info.email).first
  #    if registered_user
  #      return registered_user
  #    else
  #
  #      user = User.create(name:auth.info.first_name,
  #                          provider:auth.provider,
  #                          uid:auth.uid,
  #                          email:auth.info.email,
  #                          password:Devise.friendly_token[0,20],
  #                        )
  #    end
  #
  #  end
  #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource_or_scope)
    session.fetch 'user_return_to', recruiter_dash_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:type, :first_name, :last_name]
  end

end

app/controllers/employer_dashboard_controller.rb
class EmployerDashboardController < ApplicationController

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def sign_up
    @type = 'Employer'
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
  def google_oauth2
    auth = env["omniauth.auth"] 
    @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
 
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  
  def facebook     
     auth = env["omniauth.auth"] 
     @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)      
  
   if @user.persisted?       
    sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
    session["devise.facebook_data"] = request.env["omniauth.auth"]
    redirect_to new_user_registration_url
    end
  end

  def linkedin
      auth = env["omniauth.auth"]
      @user = User.connect_to_linkedin(request.env["omniauth.auth"],current_user)
      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.linkedin_uid"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

	def recruiter
	end

 	def employer
	end

 	def postings
	end
end

app/controllers/recruiter_dashboard_controller.rb
class RecruiterDashboardController < ApplicationController

end

app/controllers/recruiters_controller.rb
class RecruitersController < ApplicationController
  def sign_up
    @type = 'Recruiter'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employer_dashboard/index.html.erb
<h1>Nakatomi Towers Consulting</h1>

<p><strong>Total Hires: 5</strong></p>
<p><strong>Pending Hire Payments: 3</strong></p>
<p style="text-align:right">
  <button class="btn btn-large btn-primary" type="submit">
    Make Payment!
  </button>
</p>

<p><strong>Unpaid Hires</strong></p>
<div class="table-responsive">


  <table class="table">
    <th colspan="4">
    <td><strong>Name/Position</strong></td>
    <td><strong>Date Hired</strong></td>
    <td><strong>Payment Due</strong></td>
    <td><strong>Amount Due</strong></td>
    </th>

    <tr>
      <td>John Doe - Developer - Google</td>
      <td>09-13-13</td>
      <td>10-13-13</td>
      <td>$900</td>
    </tr>
    <td>Jane Smith - Analyst - Twitter</td>
    <td>10-24-13</td>
    <td>11-24-13</td>
    <td>$600</td>
    <tr>
      <td>Sergei Federov - Marketing Manager - Snapchat</td>
      <td>11-05-13</td>
      <td>12-05-13</td>
      <td>$250</td>
    </tr>

  </table>
</div>



<p><strong>Paid Hires</strong></p>
<div class="table-responsive">


  <table class="table">
    <th colspan="4">
      <tr>
        <td><strong>Name/Position</strong></td>
        <td><strong>Date Hired</strong></td>
        <td><strong>Date Paid</strong></td>
        <td><strong>Amount Paid</strong></td>
        </th>

      <tr>
        <td>Pat Solitano - Developer - Google</td>
        <td>09-13-13</td>
        <td>09-20-13</td>
        <td>$900</td>
      </tr>
    <td>Brian Urlacher - Analyst - Twitter</td>
    <td>10-24-13</td>
    <td>10-31-13</td>
    <td>$600</td>
    <tr>
      <td>Mario Yluigi - Marketing Manager - Snapchat</td>
      <td>11-05-13</td>
      <td>12-01-13</td>
      <td>$250</td>
    </tr>


  </table>
</div>


<p style="text-align:center">
  <a href="www.espn.com">Tell Others About Us!</a></p>

app/views/employers/sign_up.html.erb
<h1>Employer</h1>
<p>We are working on our Racquire App</p>

<div class="row-fluid">

  <div class="col-md-6">

    <div class="jumbotron">

      <form class="form-signin">
        <h2 class="form-signin-heading">Existing Employers</h2>
        <p>
          <input type="text" class="form-control" placeholder="Email address">
        </p>
        <p>
          <input type="password" class="form-control" placeholder="Password">
        </p>
        <label class="checkbox-center">
          <input type="checkbox" value="remember-me"> Remember me
        </label>

        <p>
          <%=link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
        </p>

      </form>
      <p style ="text-align:center; font-size:45px"><strong>OR</strong>
      </p>
      <div style="text-align:center">
        <p>
          <button class="btn btn-large btn-primary" type="submit">
            <%= link_to "Login with Linkedin",user_omniauth_authorize_path(:linkedin) %>
          </button>
      </div>
      </p>

      <p>
      <div style="text-align:center">
        <button class="btn btn-large btn-primary" type="submit">Login with Facebook</button>
      </div>
      </p>

      <p>
      <div style="text-align:center">
        <button class="btn btn-large btn-primary" type="submit">Login with Google</button>
      </div>
      </P>

    </div>

  </div>


  <div class="col-md-6">

    <div class="jumbotron">
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
        <%= devise_error_messages! %>
        <%= f.hidden_field :type, :value => @type %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: "form-control" %></div>

        <div class="form-group">
          <%= f.submit "Sign up", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Racquire", root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %><li>
        <li><%= link_to "Recruiter", recruiter_path %><li> 
        <li><%= link_to "Employer", employer_path %><li> 
        <li><%= link_to "Postings", postings_path %><li> 
        <li><%= link_to "testing", testing_path %><li> 
        <li><%= link_to "Learn", learn_path %><li>

        <% if user_signed_in? && current_user.type == 'Recruiter' %>
          <li><%= link_to "Dashboard", 'recruiter_dash'%></li>
        <% elsif user_signed_in? && current_user.type == 'Employer' %>
          <li><%= link_to "Dashboard", 'employer_dash'%></li>
        <% end %>

        <% if user_signed_in? %>         
          <li><%= link_to "Sign out", destroy_user_session_path,:method => :delete %></li>
        <% else%>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Racquire</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>	
</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on our One Month Rails Pinteresting App</p>

app/views/pages/employer.html.erb
<h1>Employer</h1>
<p>We are working on our Racqurie App</p>

<div class="row-fluid">
 
		<div class="col-md-6">

			<div class="jumbotron">
		 
			<form class="form-signin">
				 <h2 class="form-signin-heading">Existing Employer</h2>
				 <p>
				 	<input type="text" class="form-control" placeholder="Email address">
				 </p>
				 <p>
				 	<input type="password" class="form-control" placeholder="Password">
				 </p>
					 <label class="checkbox-center">
					 	<input type="checkbox" value="remember-me"> Remember me
					 </label>
				 <div>
				 	<button class="btn btn-large btn-primary" type="submit">Sign in</button>
				 </div>
			 </form>
			
							
		 </div>


		</div>



	 <div class="col-md-6">

	 	<div class="jumbotron"
	 
		<form class="form-signin">
		 <h2 class="form-signin-heading">New Employer</h2>
			 <p>
			 	<input type="text" class="form-control" placeholder="Contact Name">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Contact Phone">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Company Name">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Email address">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Password">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Confirm Password">
			 </p>
			 <label class="checkbox-center">
			 	<input type="checkbox" value="remember-me"> Remember me
			 </label>
		 <div>
		 	<button class="btn btn-large btn-primary" type="submit">Sign in</button>
		 </div>
		</form>
	 
	 </div>

	</div>
 
</div>

app/views/pages/employer_dash.html.erb
<h1>Nakatomi Towers Consulting</h1>

<p><strong>Total Hires: 5</strong></p>
<p><strong>Pending Hire Payments: 3</strong></p>
				<p style="text-align:right">
				<button class="btn btn-large btn-primary" type="submit">
       	Make Payment!
     	 	</button>
     	 </p>

<p><strong>Unpaid Hires</strong></p>
<div class="table-responsive">


	<table class="table">
    <th colspan="4">
      <td><strong>Name/Position</strong></td>
      <td><strong>Date Hired</strong></td>
      <td><strong>Payment Due</strong></td>
      <td><strong>Amount Due</strong></td>
    </th>

		<tr>
			<td>John Doe - Developer - Google</td>
		  <td>09-13-13</td>
		  <td>10-13-13</td>
		  <td>$900</td>
		</tr>
			<td>Jane Smith - Analyst - Twitter</td>
			<td>10-24-13</td>
			<td>11-24-13</td>
			<td>$600</td>
		<tr>
			<td>Sergei Federov - Marketing Manager - Snapchat</td>
			<td>11-05-13</td>
			<td>12-05-13</td>
			<td>$250</td>
		</tr>
	
	</table>
</div>



<p><strong>Paid Hires</strong></p>
<div class="table-responsive">


	<table class="table">
	 <th colspan="4">
		<tr>
			<td><strong>Name/Position</strong></td>
			<td><strong>Date Hired</strong></td>
			<td><strong>Date Paid</strong></td>
			<td><strong>Amount Paid</strong></td>
	 </th>
	  
		<tr>
			<td>Pat Solitano - Developer - Google</td>
		  <td>09-13-13</td>
		  <td>09-20-13</td>
		  <td>$900</td>
		</tr>
			<td>Brian Urlacher - Analyst - Twitter</td>
			<td>10-24-13</td>
			<td>10-31-13</td>
			<td>$600</td>
		<tr>
			<td>Mario Yluigi - Marketing Manager - Snapchat</td>
			<td>11-05-13</td>
			<td>12-01-13</td>
			<td>$250</td>
		</tr>
	
	 
	</table>
</div>


<p style="text-align:center">
<a href="www.espn.com">Tell Others About Us!</a></p>

app/views/pages/home.html.erb
<h1>Welcome to Racquire!</h1>
  <div class="jumbotron center"> 
  <p style="font-size:45px"><strong>Refer your <em>friends</em>.</strong></p>
  <p style="font-size:45px"><strong>If they get <em>hired</em>,</strong></p>
  <p style="font-size:45px"><strong>You get <em>paid</em>!</strong></p>


<p style="font-size:40px">
  Are you...
</p>
    <p>
      <%=link_to "Looking to recruit from your network?", 'recruiters/sign_up', class: "btn btn-primary btn-lg" %>
    </p>
    <p style="font-size: 30px"><strong> OR</strong></p>
     <p>
      <%=link_to "An Employer wanting to use the service?", 'employers/sign_up', class: "btn btn-primary btn-lg" %>
    </p>
</div>

app/views/pages/how_to_employer.html.erb
<h1>We want to help you find the best candidates possible</h1>
  <div class="jumbotron center"> 
  <p style="font-size:45px"><strong>Want more diverse candidates?</strong></p>
  <p style="font-size:45px"><strong>Don't want to pay recruiting firms a big commmission?</strong></p>
  <p style="font-size:45px"><strong>Use Racquire to enable outsourcing your candidate search!</strong></p>



<p style="font-size:40px">
  Are you...
</p>

    <p>
      <%=link_to "Looking to recruit from your network?", recruiter_path, class: "btn btn-primary btn-lg" %>
    </p>
    <p style="font-size: 30px"><strong> OR</strong></p>
     <p>
      <%=link_to "An Employer wanting to use the service?", employer_path, class: "btn btn-primary btn-lg" %>
    </p>
  

</div> 

app/views/pages/how_to_recruiter.html.erb
<h1>Getting Started</h1>
  <div class="jumbotron center"> 
  <p style="font-size:45px"><strong>Are your friends or colleagues</strong></p>
  <p style="font-size:45px"><strong>looking for a new job?</strong></p>
  <p style="font-size:45px"><strong>Use Racquire and help them help you!</strong></p>



<p style="font-size:40px">
  Are you...
</p>

    <p>
      <%=link_to "Looking to recruit from your network?", recruiter_path, class: "btn btn-primary btn-lg" %>
    </p>
    <p style="font-size: 30px"><strong> OR</strong></p>
     <p>
      <%=link_to "An Employer wanting to use the service?", employer_path, class: "btn btn-primary btn-lg" %>
    </p>
  

</div> 

app/views/pages/learn.html.erb
<div class= "jumbotron center">
	<h1> About Racquire </h1>
	<div class="well well-lg">
		<p>Two mice fell into a bucket of cream. The first mouse quickly gave up and drowned. The second mouse fought so hard, that eventually he churned that cream into butter and walked out. As of today, I am that second mouse.</p>
	</div>

app/views/pages/payments.html.erb
<h1>Make a payment to Racquire</h1>
<p>Please input the following information to securely send payments</p>

<div class="row-fluid">

	 <div class="col-md-6">

	 	<div class="jumbotron"
	 
		<form class="form-signin">
		 <h2 class="form-signin-heading">Payment Authorization Form</h2>
			 <p>
			 	<input type="text" class="form-control" placeholder="Name">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Email address">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Company">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Total Payment Amount">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Notes">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Payment Date">
			 </p>


		 <div>
		 	<button class="btn btn-large btn-primary" type="submit">Submit Payment</button>
		 </div>
		</form>
	 
	 </div>

	</div>
 
</div>

app/views/pages/postings.html.erb
<h1>Postings</h1>
<p>We are working on our Racquire App</p>

app/views/pages/recruiter.html.erb
<h1>Recruiter</h1>
<p>We are working on our Racquire App</p>

<div class="row-fluid">
 
		<div class="col-md-6">

			<div class="jumbotron">
		 
			<form class="form-signin">
				 <h2 class="form-signin-heading">Existing Members</h2>
				 <p>
				 	<input type="text" class="form-control" placeholder="Email address">
				 </p>
				 <p>
				 	<input type="password" class="form-control" placeholder="Password">
				 </p>
					 <label class="checkbox-center">
					 	<input type="checkbox" value="remember-me"> Remember me
					 </label>
				
				<p>
      	<%=link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
    		</p>

			 </form>
			<p style ="text-align:center; font-size:45px"><strong>OR</strong>
			</p>
			<div style="text-align:center">
          <p>
           <button class="btn btn-large btn-primary" type="submit">
           	<%= link_to "Login with Linkedin",user_omniauth_authorize_path(:linkedin) %>
           	 </button>
      </div>
         </p>
   
          <p>
      <div style="text-align:center">
           <button class="btn btn-large btn-primary" type="submit">Login with Facebook</button>
     </div>
         </p>
   
           <p>
      <div style="text-align:center">
           <button class="btn btn-large btn-primary" type="submit">Login with Google</button>
     </div>
         </P>
				
		 </div>

		</div>


	 <div class="col-md-6">

	 	<div class="jumbotron"
	 
		<form class="form-signin">
		 <h2 class="form-signin-heading">New Members</h2>
			 <p>
			 	<input type="text" class="form-control" placeholder="Name">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Email address">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Password">
			 </p>
			 <p>
			 	<input type="password" class="form-control" placeholder="Confirm Password">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Current Employer">
			 </p>
			 <p>
			 	<input type="text" class="form-control" placeholder="Current Job Title">
			 </p>
			 <p>
				 <input type="text" class="form-control" placeholder="Skills">
			 </p>
			 <label class="checkbox-center">
			 	<input type="checkbox" value="remember-me"> Remember me
			 </label>
		 <div>
		 	<button class="btn btn-large btn-primary" type="submit">Sign in</button>
		 </div>
		</form>
	 
	 </div>

	</div>
 
</div>

app/views/pages/recruiter_dash.html.erb
<h1>@user </h1>

<p><strong>Total Earned: $3000</strong></p>
<p><strong>Score: ****</strong></p>
<p><strong>Referral ID: 1234135</strong></P>
    <p>
      <%=link_to "Job Postings", postings_path, class: "btn btn-primary btn-lg" %>
    </p>
<p><strong>Referrals Hired: 3</strong></p>


<div class="table-responsive">


	<table class="table">
	 <th colspan="3">
		<tr>
			<td><strong>Name/Position</strong></td>
			<td><strong>Date Hired</strong></td>
			<td><strong>Amount Due</strong></td>
	 </th>
	  
		<tr>
			<td>John Doe - Developer - Google</td>
		  <td>09-13-13</td>
		  <td>$900</td>
		</tr>
			<td>Jane Smith - Analyst - Twitter</td>
			<td>10-24-13</td>
			<td>$600</td>
		<tr>
			<td>Sergei Federov - Marketing Manager - Snapchat</td>
			<td>11-05-13</td>
			<td>$250</td>
		</tr>
	
	 
	</table>
</div>


<p style="text-align:center">
<a href="www.espn.com">Invite Friends to Recruit</a></p>

app/views/pages/testing.html.erb
<h1>Welcome to Racquire!</h1>
  <div class="jumbotron center"> 
  <p style="font-size:45px"><strong>Refer your <em>friends</em>.</strong></p>
  <p style="font-size:45px"><strong>If they get <em>hired</em>,</strong></p>
  <p style="font-size:45px"><strong>You get <em>paid</em>!</strong></p>


<p style="font-size:40px">
  Are you...
</p>

    <p>
      <%=link_to "Looking to recruit from your network?", new_user_session_path, class: "btn btn-primary btn-lg" %>
    </p>
    <p style="font-size: 30px"><strong> OR</strong></p>
     <p>
      <%=link_to "An Employer wanting to use the service?", new_employer_session_path, class: "btn btn-primary btn-lg" %>
    </p>
  

</div> 

app/views/recruiter_dashboard/index.html.erb
<h1><%= current_user.full_name %> </h1>

<p><strong>Total Earned: $3000</strong></p>
<p><strong>Score: ****</strong></p>
<p><strong>Referral ID: 1234135</strong></P>
<p>
  <%=link_to "Job Postings", postings_path, class: "btn btn-primary btn-lg" %>
</p>
<p><strong>Referrals Hired: 3</strong></p>


<div class="table-responsive">


  <table class="table">
    <th colspan="3">
      <tr>
        <td><strong>Name/Position</strong></td>
        <td><strong>Date Hired</strong></td>
        <td><strong>Amount Due</strong></td>
        </th>

      <tr>
        <td>John Doe - Developer - Google</td>
        <td>09-13-13</td>
        <td>$900</td>
      </tr>
    <td>Jane Smith - Analyst - Twitter</td>
    <td>10-24-13</td>
    <td>$600</td>
    <tr>
      <td>Sergei Federov - Marketing Manager - Snapchat</td>
      <td>11-05-13</td>
      <td>$250</td>
    </tr>


  </table>
</div>


<p style="text-align:center">
  <a href="www.espn.com">Invite Friends to Recruit</a></p>

app/views/recruiters/sign_up.html.erb
<h1>Recruiter</h1>
<p>We are working on our Racquire App</p>

<div class="row-fluid">

  <div class="col-md-6">

    <div class="jumbotron">

      <form class="form-signin">
        <h2 class="form-signin-heading">Existing Members</h2>
        <p>
          <input type="text" class="form-control" placeholder="Email address">
        </p>
        <p>
          <input type="password" class="form-control" placeholder="Password">
        </p>
        <label class="checkbox-center">
          <input type="checkbox" value="remember-me"> Remember me
        </label>

        <p>
          <%=link_to "Login", new_user_session_path, class: "btn btn-primary btn-lg" %>
        </p>

      </form>
      <p style ="text-align:center; font-size:45px"><strong>OR</strong>
      </p>
      <div style="text-align:center">
        <p>
          <button class="btn btn-large btn-primary" type="submit">
            <%= link_to "Login with Linkedin",user_omniauth_authorize_path(:linkedin) %>
          </button>
      </div>
      </p>

      <p>
      <div style="text-align:center">
        <button class="btn btn-large btn-primary" type="submit">Login with Facebook</button>
      </div>
      </p>

      <p>
      <div style="text-align:center">
        <button class="btn btn-large btn-primary" type="submit">Login with Google</button>
      </div>
      </P>

    </div>

  </div>


  <div class="col-md-6">

    <div class="jumbotron">
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
          <%= f.hidden_field :type, :value => @type %>
          <div class="form-group">
            <%= f.label :first_name %>
            <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :last_name %>
            <%= f.text_field :last_name, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: "form-control" %></div>

          <div class="form-group">
            <%= f.submit "Sign up", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
</div>